services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/conf/:/conf/'
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    networks:
      - net
    command: neo4j
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sqs,lambda,glue,sns
      - DEFAULT_REGION=us-east-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  dgraph: